# Generated by Django 4.2.2 on 2023-07-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='категория'),
        ),
    ]
