# Generated by Django 4.2.2 on 2023-08-14 08:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skychimp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AddField(
            model_name='sending',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='sending',
            name='frequency',
            field=models.CharField(choices=[('Один раз', 'Один раз'), ('1 раз в день', '1 раз в день'), ('1 раз в неделю', '1 раз в неделю'), ('1 раз в месяц', '1 раз в месяц')], default='Один раз', max_length=14, verbose_name='Периодичность'),
        ),
        migrations.AddField(
            model_name='sending',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время рассылки'),
        ),
        migrations.AddField(
            model_name='sending',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='sending',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Завершена', 'Завершена'), ('Запущена', 'Запущена')], default='Создана', max_length=50, verbose_name='Статус'),
        ),
    ]
